# Generated by Django 6.0.3 on 2026-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='exam',
            name='copie_file',
            field=models.FileField(blank=True, help_text='La copie étudiant (Image ou PDF)', null=True, upload_to='exams/copies/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='corrige_file',
            field=models.ImageField(blank=True, help_text='Le corrigé type', null=True, upload_to='exams/corriges/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('solve', 'Résolution simple'), ('grade', 'Correction (Professeur)')], default='solve', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(help_text="L'énoncé de l'examen", upload_to='exams/enonces/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Pending', 'En attente'), ('Processing', 'En cours...'), ('Completed', 'Terminé'), ('Error', 'Erreur')], default='Pending', max_length=20),
        ),
    ]
