# Generated by Django 6.0.3 on 2026-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_exam_options_exam_copie_file_exam_corrige_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='copie_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='corrige_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mode',
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(upload_to='exams/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
