# Generated by Django 6.0.3 on 2026-04-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_exam_options_remove_exam_copie_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='mode',
            field=models.CharField(default='solve', max_length=20),
        ),
    ]
