# Generated by Django 6.0.3 on 2026-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
